language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t emibap/docker-react -f Dockerfile.dev .

script:
  - docker run emibap/docker-react npm run test -- --coverage